### ISSUE TITLE
possible packaging issues: .babelrc causes react-native not to work

### ISSUE THREAD

**Issue by vladp** [gaearon/react-deep-force-update#1]
Hello, I am having problems using react-native 0.21
According to this report  
https://github.com/facebook/react-native/issues/5393#issuecomment-174319207
it has to do with .babelrc being included in your distribution of npm.

I am not actually sure if that's the problem, or not. The solution to remove all the .babelrc from my node_modules directory does not appear to fix anything.

Therefore, I wanted to reach out to you to see if you could take a look.

my package.json does not even include deep-force-update

> 
>     "engines": {
>     "node": ">=4",
>     "npm": ">=2 <4"
>   },
> 
>     "devDependencies": {
> 	"babel-core": "^6.6.5",
>         "babel-register":"^6.6.0",
> 	"babel-eslint": "^5.0.0",
> 	"babel-loader": "^6.2.0",
>         "babel-preset-react-native": "^1.5.1",
> 	"babel-preset-es2015": "^6.6.0",
> 	"babel-preset-react": "^6.5.0",
> 	"babel-preset-stage-1": "^6.5.0",
> 	"eslint": "^2.2.0",
> 	"eslint-loader": "^1.1.1",
> 	"eslint-plugin-react": "^4.0.0",
> 	"react-native-webpack-server": "^0.8.4",
> 	"webpack": "^1.12.14",
> 	"webpack-dev-server": "^1.14.1"
>     },
> 
> 
>     "dependencies": {
> 
> 	"react-native": "^0.21.0",
> 	
> 	"@remobile/react-native-splashscreen": "^1.0.3",
> 
> 	"react-native-blur": "^0.7.10",
> 	"react-native-htmlview": "^0.2.0",
> 
> 
> 	"react-native-material-kit": "^0.3.0", 
> 	"react-native-material-design": "^0.3.3"
>     }
![react-proxy-erorr](https://cloud.githubusercontent.com/assets/94890/13552886/0a18e860-e342-11e5-9a44-cd2ebbd6c538.png)

**Comment by gaearon** [comment]
I recommend you to stop using [react-native-webpack-server](https://github.com/mjohnston/react-native-webpack-server) because it’s not actively maintained and often causes issues like this.

The latest versions of `react-deep-force-update` both for 1.x and 2.x branches do not include `.babelrc` anymore. Neither does `react-proxy`. Unfortunately I don’t think there is anything actionable in this issue for this package so I’m closing. Maybe using the official React Native packager will solve your issues.

**Comment by vladp** [comment]
Thank you for your help. I had re-examined a number of packages in my devDependecies section. And have gotten it to work.
I had upgraded to React-native 0.21 but still needed to run eslint on my sources (I had not used react-native-web-pack actually, so I removed it with no consequencies).
Big problem was between babel-eslint and other packages.

Specifically, what solved for me were these 3 things:

-  using a beta version of babel-eslint
-  including react-proxy 2.0.6, 
-  removing  "babel-preset-react-native": "^1.5.1"


In case somebody else searches for a working configuration for react-native  and eslint (until next nodejs dependency hell :-( ) here it is 

```

    "engines": {
    "node": ">=4",
    "npm": ">=2 <4"
  },

    "devDependencies": {

        "react-proxy":"^2.0.6",
        "babel-eslint": "^6.0.0-beta.1",
        
	"babel-preset-es2015": "^6.6.0",
	"babel-preset-react": "^6.5.0",
	"babel-preset-stage-1": "^6.5.0",

        
        "eslint": "~2.2.0",
	"eslint-loader": "^1.1.1",
	"eslint-plugin-react": "^4.0.0"
    },


    "dependencies": {

	"react-native": "^0.21.0",
	
	"@remobile/react-native-splashscreen": "^1.0.3",

	"react-native-blur": "^0.7.10",
	"react-native-htmlview": "^0.2.0",


	"react-native-material-kit": "^0.3.0", 
	"react-native-material-design": "^0.3.3"
    }
```

**Comment by gaearon** [comment]
I’m confused about how you use `react-proxy@2.x`. Which project depends on it? For example, `react-transform-hmr` currently uses `react-proxy@1.x`.

**Comment by vladp** [comment]
@gaearon. Sorry react-proxy@2.x was a left over (form when I was testing out things)  in my config when I pasted into the comment screen. It is not there and not needed. I had removed it from my comment above. You are correct, it is transform-hmr that uses react-proxy at 1.x level.

**Comment by gaearon** [comment]
:+1:
