### ISSUE TITLE
2.1.2 changes the module from commonJS to ES6 , causes error when install&run react-hot-loader@3.1.3

### ISSUE THREAD

**Issue by chairuosen** [gaearon/react-deep-force-update#13]
got error deepForceUpdate is not a function

reinstall 2.1.1 solved this.

**Comment by jeffryang24** [comment]
I also got the same error while my npm update the version into 2.1.2. Here the screenshot:
![error_deep_force_update](https://user-images.githubusercontent.com/8284757/44709892-f67d5e00-aad4-11e8-8f6b-573c5f1c2b62.png)

**Comment by gaearon** [comment]
Should be fixed in 2.1.3.
