### ISSUE TITLE
Update only elements that subscribe to given contextType

### ISSUE THREAD

**Issue by wmertens** [gaearon/react-deep-force-update#3]
I use this to update components that use context to get translation strings after the language was switched.

I know this uses internal APIs, but using this is much nicer than either constantly managing 100+ listeners or force-rerendering the app through a `key` on the root element.

It would be even nicer if it would only update components that use the context in the first place. Would that be difficult to do? Would you accept a PR that does this?

**Comment by iddan** [comment]
Exact use case

**Comment by neoziro** [comment]
Fixed by #6

**Comment by neoziro** [comment]
Fixed by #6

**Comment by wmertens** [comment]
@neoziro wouldn't it be nicer to provide a reference implementation of the shouldUpdate function for `contextName`-only updates?

**Comment by gaearon** [comment]
I was about to write an implementation but then realized there is a problem with #6. I filed https://github.com/gaearon/react-deep-force-update/issues/8 for it.
